import React from "react";
import Head from "next/head";
import HeroCarousel from "@/components/HeroCarousel";
import WhyUs from "@/components/WhyUs";
import OurServices from "@/components/OurServices";
import HeroAbout from "@/components/HeroAbout";
import PopularDestination from "@/components/PopularDestination";
import RecentTours from "@/components/RecentTours";
import TestiMonials from "@/components/TestiMonials";
import baseURL from "@/baseUrl";
import Chat from "@/components/chat/chat";
const Home = ({
  carouselData,
  chooseus,
  ourservices,
 
}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroCarousel data={carouselData} />
      <WhyUs data={chooseus} />
      <OurServices data={ourservices} />
      <HeroAbout />
      <PopularDestination />
      <RecentTours/>
      <TestiMonials />
      <Chat />
    </>
  );
};
export async function getStaticProps() {
  const carousel = await fetch(`${baseURL}/api/carousel`);
  const data = await carousel.json();
  const whyus = await fetch(`${baseURL}/api/chooseus`);
  const whyusData = await whyus.json();
  const ourservices = await fetch(`${baseURL}/api/ourservices`);
  const ourservicesData = await ourservices.json();
 
  return {
    props: {
      carouselData: data,
      chooseus: whyusData,
      ourservices: ourservicesData,
     
    }, // will be passed to the page component as props
  };
}
export default Home;
